name: 'Connect-VPN-debug-and-timeout'
description: 'Connect VPN + debug and timeout'
branding:
  icon: 'cast'
  color: 'green'
inputs:
  SECRET:
    description: 'Username and password for access vpn'
    required: false
    default: ''
  TLS_KEY:
    description: 'User key for access vpn'
    required: false
    default: ''
  FILE_OVPN:
    description: 'Location file open vpn'
    required: true
    default: './config.ovpn'
  TIMEOUT:
    description: 'VPN connection timout in ms'
    required: false
    default: '15000'
runs:
  using: 'node12'
  main: 'dist/index.js'
